# Generated by Django 2.2.15 on 2020-09-24 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('catalog', '0002_auto_20200923_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', help_text='Enter E-mail', max_length=254)),
                ('Address', models.TextField(default='no address', max_length=256)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
