# Generated by Django 2.2.15 on 2020-09-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200924_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='USERNAME_FIELD',
            new_name='user_name',
        ),
    ]
