# Generated by Django 2.2.15 on 2020-09-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200924_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
