# Generated by Django 2.2.15 on 2020-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200928_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_hash', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
