# Generated by Django 2.2.15 on 2020-10-05 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_account_unwanted_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=Decimal('0.0'), max_digits=18),
        ),
    ]
