# Generated by Django 2.2.15 on 2020-10-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20201005_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isCategoriesCacheSet',
            field=models.BooleanField(default=False),
        ),
    ]
