# Generated by Django 2.2.15 on 2020-10-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_account_iscategoriescacheset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isCategoriesCacheSet',
        ),
    ]
