# Generated by Django 2.2.15 on 2020-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Description',
            field=models.TextField(default='default description of dish', max_length=1000),
        ),
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', help_text='Enter E-mail', max_length=254),
        ),
    ]
