# Generated by Django 2.2.15 on 2020-09-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200924_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
