# Generated by Django 2.2.15 on 2020-09-28 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=11),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=11),
        ),
    ]
