# Generated by Django 2.2.15 on 2020-10-02 10:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201002_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unwanted_dishes',
            field=django_mysql.models.SetTextField(models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
